apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: apa
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
  rabbitmq:
    additionalConfig: |
      default_user = guest
      default_pass = guest
      # allow guest login from any host (dev only)
      loopback_users = none
  persistence:
    storage: "0"
