apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.55.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/k8s/infra/loki-values.yaml
    - repoURL: https://github.com/hamza-rx12/agentic_process_automation.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: apa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
