apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hamza-rx12/agentic_process_automation.git
    targetRevision: master
    path: k8s/infra/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: apa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Operator CRDs are large; server-side apply avoids "last-applied" limit.
      - ServerSideApply=true
